project:
  type: website
  output-dir: docs

website:
  title: "Tools and Skills for Reproducible Transport Research"
  favicon: images/icon.png
  repo-url: "https://github.com/tdscience/course"
  repo-actions: [issue]
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Materials by [Robin Lovelace](https://www.robinlovelace.net/), 2025."
  sidebar:
    background: primary
    logo: "images/tsrtr.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/tdscience/course
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      # - href: tp-schedule.qmd
      #   text: Tools and Skills for Reproducible Transport Research
      - href: materials.qmd
        text: Materials
      - href: prerequisites.qmd
        text: Prerequisites
      - section: "Examples"
        contents:
          - href: collisions.qmd
            text: Road traffic collisions
      - href: https://github.com/tdscience/course/discussions
        text: Forum

format:
  html:
    theme: lux
    # css: styles.css
    toc: true
    title-prefix: "Data Science Course - "
    number-sections: true
    author-meta: "Robin Lovelace & contributors"
    date-meta: "2025"
    copyright: "Â© 2025 Robin Lovelace"
    license: "CC BY-SA"

execute:
  freeze: false
  cache: refresh


