project:
  type: website
  output-dir: docs

website:
  title: "Data Science and Digital Tools for Transport Planning"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/tdscience/course
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: tp_schedule.qmd
        text: Data Science and Digital Tools for Transport Planning
      - href: materials.qmd
        text: Materials
      - href: https://github.com/tdscience/course/discussions
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
  cache: true

